language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: fanavarro
    token:
      secure: YuO2owvWo5HNWScthbSkiFOjuSBp7UslhhdnSx+DLG8oOnE1rXLoJG6YAwP3X6S6xSNLtFk1SC+lg9saSGWPDYf+v55T79er5cf+nhLEiPu4uKtf/mikUuohuKo75skyBkGgT5Fu69WF/oihM4000JA+Q7AYYzI8meIQiEtPCPpdsWJiFY2JkcLicCPMScd6tDmhgoUkhvGrx1jh9dFrJi5HNQ60CsXO9FrsKazgL4+tKKkgVRci2Fcg+9zVk5IOPqhpCdAPPjTy68OiSmCoX7M86VaugeAZMdoXn3OdgNQWhuTWGmRS6MnbH9Qs19JDpbabl7rIoDi7UVYxg/9f7iGf9tT3IGvIUXQHtA+7sFgokChPdQKB/62M4vJ/i0RlJnQ9AoGZNaXjPUogBXpYobBX6cXcOGJfXbC2oxhuhSnuUNKiOVt826p5uQK5B9hgdwS+hOkDC5dKk8BaDZqghPmGD3kpWsN3lAduWA7LbovjXRttd0oeCYNJdvrVNKEzajGojdhCV8gupEW9JZ9Y+D1vV3FQgDQikmETDbADd2meeVuXN7+KZX0LPG1QFS6t0LrG2ij2vXI4CcZf10JxkOAyWw8hMDnDlZ9cX4oKr2b9TKOPFsF+oYHYJbQl0WOqoWW4+E9rNS3LACe/Tha81Y8c535J5z/mdZDNtgi2P+E=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fanavarro_graphlib
after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: C7P0s4E+b8JeE3tN8JYsRBMGHb/KIGrUN9g14GCK5Wb5grLQPccAeiai/STu1lttF3xvBynRL8USM5Mav+O23gSxp93/R1sDNF1/1knmjnVf0pEtLoF9YFX75DWclelSyCDzenyb/6LK8GqRFjdbCWzCFgDtHeQdpPYSQNzq+WBtfXL5D7xU9vl8pQGarbVID5J6odhGomUzB9bi4fw5UpooVvWFrtx8FM58iBITwsdFQNXKhtQXvipCHA+85Y/ioRtR/kr+HY5Re2JHiSDK0o3g3W81zAypGMfzfyZA2rgBxXoIWS7NWVfoiZrqxg1AKcSdfk2bsRaO4LeIzlgSUu8Ve/C8N5vgPkz0Rq4T6N9lAb2sO7OCV7iXaNVAeG/SdYU43FhW8+q7H82d+0FBgKHc5SjuZ7MtdrSx1+cHpLQ0XaDOMBy1J3d3P3kztzco4vsoyIqMOQFzmUzP4by6tvhB3o7rht116BiCsTegANhngHfswSJP85Ad1dg64f8w7ZjZDD4CZfPYe0NEOiYpHfodSuGM71jNUJ4u1QDGHQxmkt33JVXPpOc7jCywuhhol+e4GeV4nmOPNvl60DgRakUhOhcCQGYqjlShAP5l/21AiDw1k5/SAkCBd9nVyo/5PJ/gJJrZ5rUKvOSZtIU1jrJ+hp5KstQYDjGeNymQCzM=
  file:
    - target/graphlib-$project_version.jar
  skip_cleanup: true
  on:
    repo: fanavarro/graphlib
    branch: master
    tags: true
  name: $project_version
  tag_name: $project_version
