dist: bionic
language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    organization: fanavarro
    token:
      secure: YuO2owvWo5HNWScthbSkiFOjuSBp7UslhhdnSx+DLG8oOnE1rXLoJG6YAwP3X6S6xSNLtFk1SC+lg9saSGWPDYf+v55T79er5cf+nhLEiPu4uKtf/mikUuohuKo75skyBkGgT5Fu69WF/oihM4000JA+Q7AYYzI8meIQiEtPCPpdsWJiFY2JkcLicCPMScd6tDmhgoUkhvGrx1jh9dFrJi5HNQ60CsXO9FrsKazgL4+tKKkgVRci2Fcg+9zVk5IOPqhpCdAPPjTy68OiSmCoX7M86VaugeAZMdoXn3OdgNQWhuTWGmRS6MnbH9Qs19JDpbabl7rIoDi7UVYxg/9f7iGf9tT3IGvIUXQHtA+7sFgokChPdQKB/62M4vJ/i0RlJnQ9AoGZNaXjPUogBXpYobBX6cXcOGJfXbC2oxhuhSnuUNKiOVt826p5uQK5B9hgdwS+hOkDC5dKk8BaDZqghPmGD3kpWsN3lAduWA7LbovjXRttd0oeCYNJdvrVNKEzajGojdhCV8gupEW9JZ9Y+D1vV3FQgDQikmETDbADd2meeVuXN7+KZX0LPG1QFS6t0LrG2ij2vXI4CcZf10JxkOAyWw8hMDnDlZ9cX4oKr2b9TKOPFsF+oYHYJbQl0WOqoWW4+E9rNS3LACe/Tha81Y8c535J5z/mdZDNtgi2P+E=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fanavarro_graphlib
after_success:
- bash <(curl -s https://codecov.io/bash)

## export GPG details
before_install:
    - gpg -v --keyserver keys.openpgp.org --refresh-keys
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --no-tty --batch
    - gpg -v --list-keys
    
install:
    mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  - provider: releases
    api_key:
      secure: "IeX7+36Y7NzjZE44AMd786VVkfOn8k09IssME6vqTujU/9sAVHgYRt+23ezyhq0DAvD/AmGi9Yx5FwyIO5jMcL1todEqmWUV98F2V0siIuujMzCn85GfG7yo/BvZRx6ajVruMikMG93YrT+M0nBPAtESEBwbfhfMoh11dRXZkKlv38q5SYS/pXZiHMZLgJrW1cL8SJND6Fs8WL7eihPjZr2FKIgrjBo/OvitTVB9koSVsxjguoebYJg6lLaxLqj3GGfjcv2se+eKUM0xd4UcXL4bBcwiw+zrbNt87k4qHNj90pPgyYZqApNGDgUd/UqqO6Taj3DbLxjuZMrAzovqF6tRqszCTUlZWg/LPxnjPK3taq7xKOgsceTRlLGmK8ipRGQRvqNCbJzS1PWSLA5gWl2sVBOQiuok2AowxrhgIXBJaJe8dQfwbo0czVlreSQx2qIC+H3H2BEl1+VfZcaA0GXTzFqiWS5VAPGWImWDIy9FswJnG+4hbIvP3Gdylwf2Fjd9bhwqxLPlNCr5hYFtlujVqd+haYuC4o/soSFtYLMblnTHtTquDg7meKRXOv36a1ERTLGaLfAor/5Qg7WZpfee1d4xoftNkF5CdBMKoE02c8Q5iPgoc+z0PPhaervF5OqXx4P0loGLY97baWO97KshJcYulSvAdIdufa/M4hw="
    file:
      - target/graphlib-$project_version.jar
    skip_cleanup: true
    on:
      repo: fanavarro/graphlib
      branch: master
      tags: true
    name: $project_version
  - provider: script
    script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
    skip_cleanup: true
    on:
      repo: fanavarro/graphlib
      branch: master
      tags: true
